version: 2.1

orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

commands:
  install_aws: # Installs AWS CLI
    steps:
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
      - run: unzip awscliv2.zip
      - run: sudo ./aws/install
        
jobs:
  install:
    docker: 
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - run: npm i
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - package.json
            - udagram/*
  build:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - attach_workspace:
          at: .
      - run: npm run build # Builds front-end & api
      - persist_to_workspace:
          root: .
          paths:
            - node_modules/*
            - package.json
            - udagram/*
  deploy:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - attach_workspace:
          at: .
      - aws-elastic-beanstalk/setup # Sets up EB CLI
      - install_aws # Install AWS CLI to deploy frontend to S3
      - run:
          name: Prepare api for deployment
          command: |
            cd udagram/udagram-api
            eb init udagram -r $AWS_DEFAULT_REGION -p node.js
            eb setenv \
            AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            JWT_SECRET=$JWT_SECRET \
            POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
            POSTGRES_USERNAME=$POSTGRES_USERNAME
      - run: npm run deploy # Deploys front-end & api



workflows:
  build_and_deploy:
    jobs:
      - install:
          filters:
            branches:
              only: master # Other jobs depend on it, so when it doesn't run, Other jobs won't
      - build:
          requires:
          - install
          context: udagram
      - deploy:
          requires:
            - build
          context: udagram # Uses secret env. variable declared in udagram